version: '3'
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - "./conf.d:/etc/nginx/conf.d"
    links:
      - server
      - client
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
  server:
    # restart: always
    image: node:8
    container_name: server
    hostname: server
    volumes:
      - "./server:/src"
      - /src/node_modules
      - "./uploads:/src/uploads"
    working_dir: /src
    command: [sh, -c, npm install && npm run dev]
    ports:
      - "3000:3000"
    networks:
      - default
    links:
      - mongo
      - mongo-secondary
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  client:
    # restart: always
    image: node:12-alpine
    container_name: client
    hostname: client
    volumes:
      - "./client2:/src"
      - "./uploads:/src/uploads"
      - client_node_modules:/src/node_modules
    working_dir: /src
    command: [sh, -c, yarn && yarn dev]
    environment:
      - PORT=8080
      - HOST=0.0.0.0
    ports:
      - "8080:8080"
    links:
      - server
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  mongo:
    # restart: always
    image: mongo
    hostname: mongo
    container_name: studyroom-guide_mongo
    volumes:
      - ./data:/data/db
      - ./backup/mongo:/backup
      - ./mongo_init:/docker-entrypoint-initdb.d
    networks:
      - default
    depends_on:
      - mongo-arbiter
    command: --replSet mongo-set
  mongo-secondary:
    image: mongo
    volumes:
      - ./data_secondary:/data/db
    networks:
      - default
    depends_on: 
      - mongo
      - mongo-arbiter
    command: --replSet mongo-set
  mongo-arbiter:
    image: mongo
    networks:
      - default
    command: --replSet mongo-set
  mongo-express:
    image: mongo-express
    # restart: always
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      # ME_CONFIG_MONGODB_SERVER will get re-written by consul-template
      - ME_CONFIG_MONGODB_SERVER=mongo
    # labels:
      # - triton.cns.services=mongo-express
    # network_mode: bridge
    # env_file: _env
    ports:
      - "8081:8081"
    links:
      - mongo

volumes:
  client_node_modules:
      